ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED';

ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS voided_by INTEGER REFERENCES users(user_id);

ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS voided_at TIMESTAMP;

ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS void_reason TEXT;
